export interface BranchData {
  id: number;
  governorate: string;
  nameAr: string;
  nameEn: string;
  addressAr: string;
  addressEn: string;
  phone: string;
}

const governorateImages: Record<string, string> = {
  damascus: "/images/branch-damascus.jpg",
  rif_damascus: "/images/branch-rif-damascus.jpg",
  aleppo: "/images/branch-aleppo.jpg",
  homs: "/images/branch-homs.jpg",
  hama: "/images/branch-hama.jpg",
  latakia: "/images/branch-latakia.jpg",
  tartous: "/images/branch-tartous.jpg",
  deir_ez_zor: "/images/branch-deir-ez-zor.jpg",
  idlib: "/images/branch-idlib.jpg",
  daraa: "/images/branch-daraa.jpg",
  raqqa: "/images/branch-raqqa.jpg",
};

export function getBranchImage(governorate: string): string {
  return governorateImages[governorate] || "/images/branch-damascus.jpg";
}

export const branches: BranchData[] = [
  {
    id: 1,
    governorate: "idlib",
    nameAr: "الفرع الرئيسي - سرمدا",
    nameEn: "Main Branch - Sarmada",
    addressAr: "برج التجارة الطابق الأول",
    addressEn: "Commerce Tower, First Floor",
    phone: "+963 968 397 594",
  },
  {
    id: 2,
    governorate: "damascus",
    nameAr: "فرع ساحة المحافظة",
    nameEn: "Muhafaza Square Branch",
    addressAr: "ساحة المحافظة مقابل فندق الشام جانب الخطوط الجوية العراقية",
    addressEn: "Muhafaza Square, opposite Cham Hotel, next to Iraqi Airways",
    phone: "+963 989 400 870",
  },
  {
    id: 3,
    governorate: "damascus",
    nameAr: "فرع باب مصلى",
    nameEn: "Bab Musalla Branch",
    addressAr: "باب مصلى أول طريق الزاهرة",
    addressEn: "Bab Musalla, beginning of Zahira Road",
    phone: "+963 984 118 709",
  },
  {
    id: 4,
    governorate: "damascus",
    nameAr: "فرع الحجاز - فكتوريا",
    nameEn: "Hijaz - Victoria Branch",
    addressAr: "الحجاز فكتوريا مقابل البريد جانب شركة هافال للشحن",
    addressEn: "Hijaz Victoria, opposite Post Office, next to Haval Shipping",
    phone: "+963 964 455 303",
  },
  {
    id: 5,
    governorate: "damascus",
    nameAr: "فرع شارع بغداد",
    nameEn: "Baghdad Street Branch",
    addressAr: "شارع بغداد جانب مأكولات الشام",
    addressEn: "Baghdad Street, next to Sham Foods",
    phone: "+963 933 333 125",
  },
  {
    id: 6,
    governorate: "aleppo",
    nameAr: "فرع حلب - شارع بارون",
    nameEn: "Aleppo - Baron Street Branch",
    addressAr: "شارع بارون مقابل مصرف التسليف فرع العبارة جانب قهوة ميلانو",
    addressEn: "Baron Street, opposite Credit Bank, next to Milano Cafe",
    phone: "+963 949 061 257",
  },
  {
    id: 7,
    governorate: "hama",
    nameAr: "فرع حماة الرئيسي",
    nameEn: "Hama Main Branch",
    addressAr: "الحاضر شارع ذي قار مقابل مدرسة هيثم عصاية",
    addressEn: "Al-Hader, Thi Qar Street, opposite Haitham Asaya School",
    phone: "+963 954 831 768",
  },
  {
    id: 8,
    governorate: "daraa",
    nameAr: "فرع درعا الرئيسي",
    nameEn: "Daraa Main Branch",
    addressAr: "شارع الجمهورية جانب بنك الشام",
    addressEn: "Republic Street, next to Bank of Sham",
    phone: "+963 989 313 300",
  },
  {
    id: 9,
    governorate: "idlib",
    nameAr: "فرع إدلب",
    nameEn: "Idlib Branch",
    addressAr: "ساحة السيرياتيل غربي مدرسة الخنساء جانب شحن مسارات",
    addressEn: "Syriatel Square, west of Al-Khansa School, next to Masarat Shipping",
    phone: "+963 969 310 300",
  },
  {
    id: 10,
    governorate: "idlib",
    nameAr: "فرع سرمدا - السوق التجاري",
    nameEn: "Sarmada - Commercial Market Branch",
    addressAr: "السوق التجاري",
    addressEn: "Commercial Market",
    phone: "+963 986 052 482",
  },
  {
    id: 11,
    governorate: "damascus",
    nameAr: "فرع العباسيين",
    nameEn: "Abbasiyyin Branch",
    addressAr: "دوار العباسيين جانب بنك بيمو السعودي الفرنسي",
    addressEn: "Abbasiyyin Square, next to BEMO Saudi Fransi Bank",
    phone: "+963 947 838 733",
  },
  {
    id: 12,
    governorate: "rif_damascus",
    nameAr: "فرع تل منين",
    nameEn: "Tal Mnin Branch",
    addressAr: "تل منين دوار النخلة تقاطع الضاحية",
    addressEn: "Tal Mnin, Palm Roundabout, Dahiya Intersection",
    phone: "+963 994 929 885",
  },
  {
    id: 13,
    governorate: "damascus",
    nameAr: "فرع شارع النصر",
    nameEn: "Nasr Street Branch",
    addressAr: "شارع النصر مقابل تمثال صلاح الدين وقلعة دمشق",
    addressEn: "Nasr Street, opposite Saladin Statue and Damascus Citadel",
    phone: "+963 944 493 839",
  },
  {
    id: 14,
    governorate: "rif_damascus",
    nameAr: "فرع الكسوة",
    nameEn: "Kiswa Branch",
    addressAr: "مقابل المخفر جانب مطعم الفهد",
    addressEn: "Opposite the police station, next to Al-Fahd Restaurant",
    phone: "+963 993 563 631",
  },
  {
    id: 15,
    governorate: "latakia",
    nameAr: "فرع اللاذقية",
    nameEn: "Latakia Branch",
    addressAr: "جانب دوار هارون مقابل مبنى الهجرة والجوازات",
    addressEn: "Next to Haroun Roundabout, opposite Immigration & Passports Building",
    phone: "+963 997 644 907",
  },
  {
    id: 16,
    governorate: "tartous",
    nameAr: "فرع طرطوس",
    nameEn: "Tartous Branch",
    addressAr: "دخلة كراج القدموس مقابل الحديقة العامة",
    addressEn: "Qadmous Garage entrance, opposite Public Park",
    phone: "+963 985 133 666",
  },
  {
    id: 17,
    governorate: "daraa",
    nameAr: "فرع نصيب (قيد التجهيز)",
    nameEn: "Nasib Branch (Coming Soon)",
    addressAr: "بوابة الجمارك – جانب استراحة النخيل",
    addressEn: "Customs Gate, next to Palm Rest House",
    phone: "+963 989 313 300",
  },
  {
    id: 18,
    governorate: "hama",
    nameAr: "فرع حماة - وكيل",
    nameEn: "Hama Agent Branch",
    addressAr: "الحاضر جانب جنيد وعروتني وعسكر مقابل القحف سابقاً",
    addressEn: "Al-Hader, next to Junaid, Arutni & Askar",
    phone: "+963 933 857 271",
  },
  {
    id: 19,
    governorate: "homs",
    nameAr: "فرع حمص - وكيل",
    nameEn: "Homs Agent Branch",
    addressAr: "الدبلان شارع نادي الضباط مقابل نادي الضباط",
    addressEn: "Dablan, Officers Club Street, opposite Officers Club",
    phone: "+963 991 894 858",
  },
  {
    id: 20,
    governorate: "deir_ez_zor",
    nameAr: "فرع دير الزور",
    nameEn: "Deir ez-Zor Branch",
    addressAr: "دوار الحويجة جانب مركز سيرياتيل",
    addressEn: "Huweija Roundabout, next to Syriatel Center",
    phone: "+963 989 400 890",
  },
  {
    id: 21,
    governorate: "daraa",
    nameAr: "فرع درعا الصنمين",
    nameEn: "Daraa - Sanamein Branch",
    addressAr: "الطريق الرئيسي مدخل الكتيبة الطبية",
    addressEn: "Main Road, Medical Battalion Entrance",
    phone: "+963 992 777 401",
  },
  {
    id: 22,
    governorate: "daraa",
    nameAr: "فرع درعا الجيزة",
    nameEn: "Daraa - Jiza Branch",
    addressAr: "جنوب المسجد الكبير بجانب مجوهرات أوغاريت",
    addressEn: "South of Grand Mosque, next to Ugarit Jewelry",
    phone: "+963 934 393 810",
  },
  {
    id: 23,
    governorate: "daraa",
    nameAr: "فرع درعا بصرى الشام",
    nameEn: "Daraa - Bosra Al-Sham Branch",
    addressAr: "غرب باب الهوى 350 متر",
    addressEn: "350m west of Bab Al-Hawa",
    phone: "+963 934 393 811",
  },
  {
    id: 24,
    governorate: "raqqa",
    nameAr: "فرع الرقة",
    nameEn: "Raqqa Branch",
    addressAr: "شارع الأماسي",
    addressEn: "Amasi Street",
    phone: "+963 932 963 805",
  },
  {
    id: 25,
    governorate: "deir_ez_zor",
    nameAr: "فرع الميادين 1",
    nameEn: "Mayadin Branch 1",
    addressAr: "جانب نقليات القدموس",
    addressEn: "Next to Qadmous Transport",
    phone: "+963 998 272 827",
  },
  {
    id: 26,
    governorate: "deir_ez_zor",
    nameAr: "فرع الميادين 2",
    nameEn: "Mayadin Branch 2",
    addressAr: "شارع أنس بن مالك",
    addressEn: "Anas bin Malik Street",
    phone: "+963 989 400 842",
  },
  {
    id: 27,
    governorate: "idlib",
    nameAr: "فرع إدلب - شارع الجلاء",
    nameEn: "Idlib - Jalaa Street Branch",
    addressAr: "شارع الجلاء مقابل صيدلية نسرين",
    addressEn: "Jalaa Street, opposite Nisreen Pharmacy",
    phone: "+963 998 272 827",
  },
  {
    id: 28,
    governorate: "idlib",
    nameAr: "فرع معرة النعمان 1",
    nameEn: "Maarat Al-Numan Branch 1",
    addressAr: "شارع الكورنيش غربي ساحة الجامع",
    addressEn: "Corniche Street, west of Mosque Square",
    phone: "+963 991 150 997",
  },
  {
    id: 29,
    governorate: "idlib",
    nameAr: "فرع معرة النعمان 2",
    nameEn: "Maarat Al-Numan Branch 2",
    addressAr: "نزلة السرايا جانب مكتب الهرم",
    addressEn: "Saraya Descent, next to Al-Haram Office",
    phone: "+963 964 455 300",
  },
  {
    id: 30,
    governorate: "idlib",
    nameAr: "فرع خان شيخون",
    nameEn: "Khan Shaykhun Branch",
    addressAr: "جانب مؤسسة الكهرباء",
    addressEn: "Next to Electricity Company",
    phone: "+963 945 736 182",
  },
  {
    id: 31,
    governorate: "idlib",
    nameAr: "فرع سراقب",
    nameEn: "Saraqib Branch",
    addressAr: "طريق أبو ظهور مقابل سوق الهال",
    addressEn: "Abu Dhuhur Road, opposite Wholesale Market",
    phone: "+963 982 178 681",
  },
  {
    id: 32,
    governorate: "idlib",
    nameAr: "فرع الدانا",
    nameEn: "Dana Branch",
    addressAr: "سوق الذهب جانب فينيسيا مول",
    addressEn: "Gold Market, next to Venezia Mall",
    phone: "+963 976 482 456",
  },
  {
    id: 33,
    governorate: "idlib",
    nameAr: "فرع أريحا",
    nameEn: "Ariha Branch",
    addressAr: "أول دخلة السوق",
    addressEn: "Market Entrance",
    phone: "+963 939 074 435",
  },
  {
    id: 34,
    governorate: "idlib",
    nameAr: "فرع عقربات",
    nameEn: "Aqrabat Branch",
    addressAr: "جانب مشفى عقربات",
    addressEn: "Next to Aqrabat Hospital",
    phone: "+963 940 351 539",
  },
  {
    id: 35,
    governorate: "idlib",
    nameAr: "فرع سلقين",
    nameEn: "Salqin Branch",
    addressAr: "سوق الصاغة جانب الجامع",
    addressEn: "Goldsmith Market, next to the Mosque",
    phone: "+963 992 917 893",
  },
  {
    id: 36,
    governorate: "idlib",
    nameAr: "فرع كفر تخاريم",
    nameEn: "Kafr Takharim Branch",
    addressAr: "كفرتخاريم – شارع هنانو",
    addressEn: "Kafr Takharim, Hanano Street",
    phone: "+963 955 274 168",
  },
  {
    id: 37,
    governorate: "aleppo",
    nameAr: "فرع عفرين",
    nameEn: "Afrin Branch",
    addressAr: "الشارع الرئيسي",
    addressEn: "Main Street",
    phone: "+963 988 546 372",
  },
  {
    id: 38,
    governorate: "aleppo",
    nameAr: "فرع الباب 1",
    nameEn: "Al-Bab Branch 1",
    addressAr: "مقابل الكراج مقابل صيدلية العثمان",
    addressEn: "Opposite the Garage, opposite Othman Pharmacy",
    phone: "+963 988 546 373",
  },
  {
    id: 39,
    governorate: "aleppo",
    nameAr: "فرع اعزاز",
    nameEn: "Azaz Branch",
    addressAr: "شارع المشفى النسائي مقابل آغا ستور",
    addressEn: "Women's Hospital Street, opposite Agha Store",
    phone: "+963 988 546 374",
  },
  {
    id: 40,
    governorate: "aleppo",
    nameAr: "فرع الباب 2",
    nameEn: "Al-Bab Branch 2",
    addressAr: "جنوب دوار السنتر",
    addressEn: "South of Center Roundabout",
    phone: "+963 988 546 375",
  },
  {
    id: 41,
    governorate: "homs",
    nameAr: "فرع حمص - دوار الجامعة",
    nameEn: "Homs - University Roundabout Branch",
    addressAr: "دوار الجامعة مدخل كرم الشامي",
    addressEn: "University Roundabout, Karam Al-Shami Entrance",
    phone: "+963 952 379 916",
  },
  {
    id: 42,
    governorate: "latakia",
    nameAr: "فرع اللاذقية - الزراعة",
    nameEn: "Latakia - Ziraa Branch",
    addressAr: "الزراعة بجانب كازية حورية",
    addressEn: "Ziraa area, next to Houriya Gas Station",
    phone: "+963 932 655 145",
  },
  {
    id: 43,
    governorate: "idlib",
    nameAr: "فرع سرمين",
    nameEn: "Sarmin Branch",
    addressAr: "سرمين الشارع الرئيسي",
    addressEn: "Sarmin, Main Street",
    phone: "+963 940 568 107",
  },
  {
    id: 44,
    governorate: "aleppo",
    nameAr: "فرع حلب - الكلاسة",
    nameEn: "Aleppo - Kallasa Branch",
    addressAr: "الكلاسة المنطقة الصناعية جسر الحج",
    addressEn: "Kallasa, Industrial Area, Jisr Al-Haj",
    phone: "+963 993 355 908",
  },
  {
    id: 45,
    governorate: "aleppo",
    nameAr: "فرع حلب - العزيزية",
    nameEn: "Aleppo - Aziziya Branch",
    addressAr: "العزيزية شارع الميشية جانب صيدلية مطيع",
    addressEn: "Aziziya, Mishiyeh Street, next to Muti Pharmacy",
    phone: "+963 993 355 912",
  },
  {
    id: 46,
    governorate: "hama",
    nameAr: "فرع سلمية",
    nameEn: "Salamiyah Branch",
    addressAr: "سلمية البلد طريق حماة",
    addressEn: "Salamiyah Town, Hama Road",
    phone: "+963 992 907 875",
  },
  {
    id: 47,
    governorate: "hama",
    nameAr: "فرع محردة",
    nameEn: "Muhrada Branch",
    addressAr: "دوار الطابات محردة",
    addressEn: "Tabat Roundabout, Muhrada",
    phone: "+963 990 323 280",
  },
  {
    id: 48,
    governorate: "damascus",
    nameAr: "فرع الزبلطاني",
    nameEn: "Zablatani Branch",
    addressAr: "دخلة الجامع خلف الهجرة والجوازات",
    addressEn: "Mosque Alley, behind Immigration & Passports",
    phone: "+963 934 393 810",
  },
  {
    id: 49,
    governorate: "daraa",
    nameAr: "فرع درعا الكرك",
    nameEn: "Daraa - Karak Branch",
    addressAr: "الكرك الشرقي وسط البلد الشارع الرئيسي مجمع آدام مول محل رقم 1",
    addressEn: "East Karak, Downtown, Main Street, Adam Mall, Shop No. 1",
    phone: "+963 994 873 052",
  },
  {
    id: 50,
    governorate: "daraa",
    nameAr: "فرع درعا أزرع",
    nameEn: "Daraa - Izra Branch",
    addressAr: "أزرع ساحة بصرى",
    addressEn: "Izra, Bosra Square",
    phone: "+963 998 526 080",
  },
  {
    id: 51,
    governorate: "rif_damascus",
    nameAr: "فرع الكسوة - الأوتستراد",
    nameEn: "Kiswa - Highway Branch",
    addressAr: "كازية العابد الكسوة أوتستراد دمشق درعا",
    addressEn: "Al-Abed Gas Station, Kiswa, Damascus-Daraa Highway",
    phone: "+963 933 567 662",
  },
  {
    id: 52,
    governorate: "damascus",
    nameAr: "فرع القصور",
    nameEn: "Qusour Branch",
    addressAr: "القصور شارع الكندي جانب شاورما الرحمة",
    addressEn: "Qusour, Kindi Street, next to Rahma Shawarma",
    phone: "+963 966 136 615",
  },
  {
    id: 53,
    governorate: "rif_damascus",
    nameAr: "فرع حوش بلاس",
    nameEn: "Housh Blas Branch",
    addressAr: "حوش بلاس",
    addressEn: "Housh Blas",
    phone: "+963 984 118 709",
  },
  {
    id: 54,
    governorate: "idlib",
    nameAr: "فرع سرمدا - طريق الدانا",
    nameEn: "Sarmada - Dana Road Branch",
    addressAr: "سرمدا طريق الدانا شمال برج التجارة بـ 100 متر على اليسار",
    addressEn: "Sarmada, Dana Road, 100m north of Commerce Tower, on the left",
    phone: "+963 960 983 559",
  },
  {
    id: 55,
    governorate: "idlib",
    nameAr: "فرع كفرنبل",
    nameEn: "Kafranbel Branch",
    addressAr: "مقابل الجامع",
    addressEn: "Opposite the Mosque",
    phone: "+963 937 990 147",
  },
  {
    id: 56,
    governorate: "rif_damascus",
    nameAr: "فرع جديدة عرطوز",
    nameEn: "Jdeidet Artouz Branch",
    addressAr: "جديدة عرطوز الشارع الرئيسي السلالم قبل مفرق صحنايا",
    addressEn: "Jdeidet Artouz, Main Street, before Sahnaya Junction",
    phone: "+963 958 265 737",
  },
  {
    id: 57,
    governorate: "rif_damascus",
    nameAr: "فرع يبرود",
    nameEn: "Yabroud Branch",
    addressAr: "يبرود ساحة عردة باتجاه النبك 50 متر على اليسار الياسر للتجهيزات",
    addressEn: "Yabroud, Arda Square, 50m towards Nabk, Al-Yaser Supplies",
    phone: "+963 985 415 525",
  },
  {
    id: 58,
    governorate: "tartous",
    nameAr: "فرع بانياس",
    nameEn: "Baniyas Branch",
    addressAr: "طلعة المركز الثقافي جانب مفروشات النور",
    addressEn: "Cultural Center Hill, next to Al-Nour Furniture",
    phone: "+963 944 781 357",
  },
  {
    id: 59,
    governorate: "daraa",
    nameAr: "فرع درعا جاسم",
    nameEn: "Daraa - Jasim Branch",
    addressAr: "جاسم دوار أبو تمام",
    addressEn: "Jasim, Abu Tammam Roundabout",
    phone: "+963 941 879 079",
  },
  {
    id: 60,
    governorate: "daraa",
    nameAr: "فرع درعا صيدا",
    nameEn: "Daraa - Saida Branch",
    addressAr: "صيدا الطريق العام مقابل مفرق الغرية",
    addressEn: "Saida, Main Road, opposite Ghariya Junction",
    phone: "+963 989 313 300",
  },
  {
    id: 61,
    governorate: "aleppo",
    nameAr: "فرع حلب - المدينة الصناعية",
    nameEn: "Aleppo - Sheikh Najjar Industrial City Branch",
    addressAr: "المدينة الصناعية الشيخ نجار جانب بنك بيمو",
    addressEn: "Sheikh Najjar Industrial City, next to BEMO Bank",
    phone: "+963 960 983 565",
  },
  {
    id: 62,
    governorate: "homs",
    nameAr: "فرع حمص - سوق المسقوف",
    nameEn: "Homs - Covered Market Branch",
    addressAr: "سوق المسقوف جانب الجامع الكبير",
    addressEn: "Covered Market, next to Grand Mosque",
    phone: "+963 998 856 405",
  },
  {
    id: 63,
    governorate: "daraa",
    nameAr: "فرع درعا الحراك",
    nameEn: "Daraa - Hirak Branch",
    addressAr: "وسط البلد",
    addressEn: "Downtown",
    phone: "+963 934 393 381",
  },
  {
    id: 64,
    governorate: "daraa",
    nameAr: "فرع درعا داعل",
    nameEn: "Daraa - Dael Branch",
    addressAr: "وسط البلد",
    addressEn: "Downtown",
    phone: "+963 934 393 381",
  },
  {
    id: 65,
    governorate: "damascus",
    nameAr: "فرع شارع 29 أيار",
    nameEn: "29 Ayyar Street Branch",
    addressAr: "شارع 29 أيار جانب وكالة جوتا",
    addressEn: "29 Ayyar Street, next to Ghouta Agency",
    phone: "+963 934 393 381",
  },
];
