export interface BranchData {
  id: number;
  governorate: string;
  nameAr: string;
  nameEn: string;
  addressAr: string;
  addressEn: string;
  phone: string;
  status?: 'ACTIVE' | 'HIDDEN';
}

export const branches: BranchData[] = [
  // ── إدلب ──────────────────────────────────────────────────
  {
    id: 1,
    governorate: 'idlib',
    nameAr: 'فرع سرمدا الرئيسي',
    nameEn: 'Sarmada Main Branch',
    addressAr: 'برج التجارة الطابق الأول مكتب رقم 2',
    addressEn: 'Commerce Tower, First Floor, Office No. 2',
    phone: '0968397594',
    status: 'ACTIVE',
  },
  {
    id: 2,
    governorate: 'idlib',
    nameAr: 'فرع إدلب',
    nameEn: 'Idlib Branch',
    addressAr: 'ساحة السريانيتل غرب مدرسة الخنساء جانب شحن مسارات',
    addressEn: 'Syriatel Square, west of Al-Khansa School, next to Masarat Shipping',
    phone: '0969310300',
    status: 'ACTIVE',
  },
  {
    id: 3,
    governorate: 'idlib',
    nameAr: 'فرع سرمدا - دوار أبو رستم',
    nameEn: 'Sarmada - Abu Rustum Roundabout Branch',
    addressAr: 'غربي دوار أبو رستم',
    addressEn: 'West of Abu Rustum Roundabout',
    phone: '0995403753',
    status: 'ACTIVE',
  },
  {
    id: 4,
    governorate: 'idlib',
    nameAr: 'فرع إدلب - شارع الجلاء',
    nameEn: 'Idlib - Jalaa Street Branch',
    addressAr: 'شارع الجلاء مقابل صيدلية نسرين',
    addressEn: 'Jalaa Street, opposite Nisreen Pharmacy',
    phone: '0998272827',
    status: 'ACTIVE',
  },
  {
    id: 5,
    governorate: 'idlib',
    nameAr: 'فرع معرة النعمان - الكورنيش',
    nameEn: 'Maarat Al-Numan - Corniche Branch',
    addressAr: 'شارع الكورنيش غربي ساحة الجامع',
    addressEn: 'Corniche Street, west of Mosque Square',
    phone: '0991150997',
    status: 'ACTIVE',
  },
  {
    id: 6,
    governorate: 'idlib',
    nameAr: 'فرع معرة النعمان - السراية',
    nameEn: 'Maarat Al-Numan - Saraya Branch',
    addressAr: 'نزلة السراية جانب مكتب الهرم',
    addressEn: 'Saraya Descent, next to Al-Haram Office',
    phone: '0964455300',
    status: 'ACTIVE',
  },
  {
    id: 7,
    governorate: 'idlib',
    nameAr: 'فرع خان شيخون',
    nameEn: 'Khan Shaykhun Branch',
    addressAr: 'جانب مؤسسة الكهرباء',
    addressEn: 'Next to Electricity Company',
    phone: '0945736182',
    status: 'ACTIVE',
  },
  {
    id: 8,
    governorate: 'idlib',
    nameAr: 'فرع أبو ظهور',
    nameEn: 'Abu Dhuhur Branch',
    addressAr: 'طريق أبو ظهور جانب سوق الهال',
    addressEn: 'Abu Dhuhur Road, next to Wholesale Market',
    phone: '0982178681',
    status: 'ACTIVE',
  },
  {
    id: 9,
    governorate: 'idlib',
    nameAr: 'فرع الدانا',
    nameEn: 'Dana Branch',
    addressAr: 'شارع المولات',
    addressEn: 'Al-Moulat Street',
    phone: '0976482456',
    status: 'ACTIVE',
  },
  {
    id: 10,
    governorate: 'idlib',
    nameAr: 'فرع أريحا',
    nameEn: 'Ariha Branch',
    addressAr: 'أول دخلة السوق',
    addressEn: 'Market Entrance',
    phone: '0939074435',
    status: 'ACTIVE',
  },
  {
    id: 11,
    governorate: 'idlib',
    nameAr: 'فرع عفرين',
    nameEn: 'Afrin Branch',
    addressAr: 'جانب مشفى عفرين',
    addressEn: 'Next to Afrin Hospital',
    phone: '0940351539',
    status: 'ACTIVE',
  },
  {
    id: 12,
    governorate: 'idlib',
    nameAr: 'فرع سلفين',
    nameEn: 'Salqin Branch',
    addressAr: 'سوق الصاغة جانب عيارة جامع الروضة',
    addressEn: 'Goldsmith Market, next to Al-Rawda Mosque',
    phone: '0992917893',
    status: 'ACTIVE',
  },
  {
    id: 13,
    governorate: 'idlib',
    nameAr: 'فرع كفرنبل',
    nameEn: 'Kafranbel Branch',
    addressAr: 'مقابل الجامع',
    addressEn: 'Opposite the Mosque',
    phone: '0937990147',
    status: 'ACTIVE',
  },
  {
    id: 14,
    governorate: 'idlib',
    nameAr: 'فرع سرمين',
    nameEn: 'Sarmin Branch',
    addressAr: 'سرمين الطريق الرئيسي',
    addressEn: 'Sarmin, Main Road',
    phone: '0940568107',
    status: 'ACTIVE',
  },

  // ── دمشق ──────────────────────────────────────────────────
  {
    id: 15,
    governorate: 'damascus',
    nameAr: 'فرع دمشق الرئيسي',
    nameEn: 'Damascus Main Branch',
    addressAr: 'ساحة المحافظة مقابل فندق الشام جانب الخطوط الجوية العراقية',
    addressEn: 'Muhafaza Square, opposite Cham Hotel, next to Iraqi Airways',
    phone: '0989400870',
    status: 'ACTIVE',
  },
  {
    id: 16,
    governorate: 'damascus',
    nameAr: 'فرع باب مصلى',
    nameEn: 'Bab Musalla Branch',
    addressAr: 'باب مصلى أول طريق الزاهرة',
    addressEn: 'Bab Musalla, beginning of Zahira Road',
    phone: '0984118709',
    status: 'ACTIVE',
  },
  {
    id: 17,
    governorate: 'damascus',
    nameAr: 'فرع الحجاز - فكتوريا',
    nameEn: 'Hijaz - Victoria Branch',
    addressAr: 'الحجاز فكتوريا مقابل البريد جانب شركة هافال للشحن',
    addressEn: 'Hijaz Victoria, opposite Post Office, next to Haval Shipping',
    phone: '0964455303',
    status: 'ACTIVE',
  },
  {
    id: 18,
    governorate: 'damascus',
    nameAr: 'فرع شارع بغداد',
    nameEn: 'Baghdad Street Branch',
    addressAr: 'شارع بغداد جانب مأكولات الشام',
    addressEn: 'Baghdad Street, next to Sham Foods',
    phone: '0933333125',
    status: 'ACTIVE',
  },
  {
    id: 19,
    governorate: 'damascus',
    nameAr: 'فرع العباسيين',
    nameEn: 'Abbasiyyin Branch',
    addressAr: 'دوار العباسيين جانب بنك بيمو السعودي الفرنسي',
    addressEn: 'Abbasiyyin Square, next to BEMO Saudi Fransi Bank',
    phone: '0947838733',
    status: 'ACTIVE',
  },
  {
    id: 20,
    governorate: 'damascus',
    nameAr: 'فرع القصور',
    nameEn: 'Qusour Branch',
    addressAr: 'شارع الكنف جانب شارع سمر',
    addressEn: 'Kanaf Street, next to Samar Street',
    phone: '0966136615',
    status: 'ACTIVE',
  },
  {
    id: 21,
    governorate: 'damascus',
    nameAr: 'فرع المناطلبي',
    nameEn: 'Mnatlabi Branch',
    addressAr: 'المناطلبي شارع الملك فيصل',
    addressEn: 'Mnatlabi, King Faisal Street',
    phone: '0956623899',
    status: 'HIDDEN',
  },
  {
    id: 22,
    governorate: 'damascus',
    nameAr: 'فرع السعلان',
    nameEn: 'Saalaan Branch',
    addressAr: 'السعلان',
    addressEn: 'Al-Saalaan',
    phone: '0933265980',
    status: 'HIDDEN',
  },
  {
    id: 23,
    governorate: 'damascus',
    nameAr: 'فرع شارع النصر',
    nameEn: 'Nasr Street Branch',
    addressAr: 'شارع النصر مقابل تمثال صلاح الدين وقلعة دمشق',
    addressEn: 'Nasr Street, opposite Saladin Statue and Damascus Citadel',
    phone: '0944493839',
    status: 'ACTIVE',
  },
  {
    id: 24,
    governorate: 'damascus',
    nameAr: 'فرع السيدة زينب',
    nameEn: 'Sayyida Zaynab Branch',
    addressAr: 'السيدة زينب الطريق العام',
    addressEn: 'Sayyida Zaynab, Main Road',
    phone: '0989313300',
    status: 'ACTIVE',
  },
  {
    id: 25,
    governorate: 'damascus',
    nameAr: 'فرع جرمانا',
    nameEn: 'Jaramana Branch',
    addressAr: 'جرمانا ساحة الرئيس',
    addressEn: 'Jaramana, President Square',
    phone: '0968410286',
    status: 'HIDDEN',
  },
  {
    id: 26,
    governorate: 'damascus',
    nameAr: 'فرع الكسوة',
    nameEn: 'Kiswa Branch',
    addressAr: 'مقابل المخفر جانب مقطع النهد',
    addressEn: 'Opposite the Police Station, next to Al-Nahd Junction',
    phone: '0993563631',
    status: 'ACTIVE',
  },
  {
    id: 27,
    governorate: 'damascus',
    nameAr: 'فرع دمشق الجمهورية',
    nameEn: 'Damascus - Republic Street Branch',
    addressAr: 'شارع الجمهورية جانب بنك الشام',
    addressEn: 'Republic Street, next to Bank of Sham',
    phone: '0989313300',
    status: 'ACTIVE',
  },

  // ── ريف دمشق ──────────────────────────────────────────────
  {
    id: 28,
    governorate: 'rif_damascus',
    nameAr: 'فرع جديدة عرطوز',
    nameEn: 'Jdeidet Artouz Branch',
    addressAr: 'الشارع الرئيسي السلالم قبل مفرق صحنايا',
    addressEn: 'Main Street, before Sahnaya Junction',
    phone: '0988800714',
    status: 'ACTIVE',
  },
  {
    id: 29,
    governorate: 'rif_damascus',
    nameAr: 'فرع الزبلطاني',
    nameEn: 'Zablatani Branch',
    addressAr: 'حلة الجامع خلف الهجرة والجوازات',
    addressEn: 'Mosque Alley, behind Immigration & Passports',
    phone: '0934393810',
    status: 'ACTIVE',
  },
  {
    id: 30,
    governorate: 'rif_damascus',
    nameAr: 'فرع كارية',
    nameEn: 'Kariya Branch',
    addressAr: 'كارية طريق درعا',
    addressEn: 'Kariya, Daraa Road',
    phone: '0933567662',
    status: 'ACTIVE',
  },
  {
    id: 31,
    governorate: 'rif_damascus',
    nameAr: 'فرع تل منين',
    nameEn: 'Tal Mnin Branch',
    addressAr: 'تل منين دوار المنطلق تقاطع الضاحية',
    addressEn: 'Tal Mnin, Al-Muntalaq Roundabout, Dahiya Intersection',
    phone: '0994929885',
    status: 'ACTIVE',
  },

  // ── حلب ──────────────────────────────────────────────────
  {
    id: 32,
    governorate: 'aleppo',
    nameAr: 'فرع حلب - شارع بارون',
    nameEn: 'Aleppo - Baron Street Branch',
    addressAr: 'شارع بارون مقابل مصرف التسليف فرع العيارة جانب قهوة ميلاتو',
    addressEn: 'Baron Street, opposite Credit Bank, next to Milato Cafe',
    phone: '0949061257',
    status: 'ACTIVE',
  },
  {
    id: 33,
    governorate: 'aleppo',
    nameAr: 'فرع حلب - الكلاسة',
    nameEn: 'Aleppo - Kallasa Branch',
    addressAr: 'الكلاسة المنطقة الصناعية جسر الحج',
    addressEn: 'Kallasa, Industrial Zone, Jisr Al-Haj',
    phone: '0993355908',
    status: 'ACTIVE',
  },
  {
    id: 34,
    governorate: 'aleppo',
    nameAr: 'فرع حلب - الفيض',
    nameEn: 'Aleppo - Fayd Branch',
    addressAr: 'الفيض جانب صيدلية الكرمان',
    addressEn: 'Al-Fayd, next to Al-Karman Pharmacy',
    phone: '0984056435',
    status: 'HIDDEN',
  },
  {
    id: 35,
    governorate: 'aleppo',
    nameAr: 'فرع حلب - بستان الصناعة',
    nameEn: 'Aleppo - Industrial Garden Branch',
    addressAr: 'بستان الصناعة نزلة جامع بدر جانب الصباغ مقابل مجوهرات روائع',
    addressEn: 'Industrial Garden, Badr Mosque descent, next to jewelers',
    phone: '0944634753',
    status: 'HIDDEN',
  },
  {
    id: 36,
    governorate: 'aleppo',
    nameAr: 'فرع حلب - العزيزية',
    nameEn: 'Aleppo - Aziziya Branch',
    addressAr: 'العزيزية بيت المبيضيه جانب صيدلية مطبع',
    addressEn: 'Aziziya, Al-Mubaydah House, next to Matba Pharmacy',
    phone: '0993355912',
    status: 'HIDDEN',
  },

  // ── حماة ──────────────────────────────────────────────────
  {
    id: 37,
    governorate: 'hama',
    nameAr: 'فرع حماة الرئيسي',
    nameEn: 'Hama Main Branch',
    addressAr: 'أول طلعة الجب مفرق الصحة مقابل مدرسة مفليح عصبانية',
    addressEn: 'Top of Jub Hill, Health Junction, opposite Muflieh School',
    phone: '0946119140',
    status: 'ACTIVE',
  },
  {
    id: 38,
    governorate: 'hama',
    nameAr: 'فرع الحاضر',
    nameEn: 'Al-Hader Branch',
    addressAr: 'الحاضر جانب جنديد وعروتني وعسكر القحف سابقاً',
    addressEn: 'Al-Hader, next to former Al-Qahf military location',
    phone: '0993857271',
    status: 'ACTIVE',
  },
  {
    id: 39,
    governorate: 'hama',
    nameAr: 'فرع المحردة',
    nameEn: 'Muhrada Branch',
    addressAr: 'دوار الطيبات المحردة',
    addressEn: 'Al-Tayyibat Roundabout, Muhrada',
    phone: '0990323280',
    status: 'HIDDEN',
  },

  // ── حمص ──────────────────────────────────────────────────
  {
    id: 40,
    governorate: 'homs',
    nameAr: 'فرع حمص الرئيسي',
    nameEn: 'Homs Main Branch',
    addressAr: 'مقابل جامع حمص صبراء جانب الجامع الكبير',
    addressEn: 'Opposite Homs Sabraa Mosque, next to Grand Mosque',
    phone: '0984571627',
    status: 'ACTIVE',
  },
  {
    id: 41,
    governorate: 'homs',
    nameAr: 'فرع حمص - دوار الساعة',
    nameEn: 'Homs - Clock Roundabout Branch',
    addressAr: 'دوار الساعة القديمة خلف المصرف التجاري',
    addressEn: 'Old Clock Roundabout, behind Commercial Bank',
    phone: '0969967150',
    status: 'ACTIVE',
  },
  {
    id: 42,
    governorate: 'homs',
    nameAr: 'فرع حمص - دوار الجامعة',
    nameEn: 'Homs - University Roundabout Branch',
    addressAr: 'دوار الجامعة مدخل كريم الشامي',
    addressEn: 'University Roundabout, Karim Al-Shami Entrance',
    phone: '0952379916',
    status: 'ACTIVE',
  },

  // ── درعا ──────────────────────────────────────────────────
  {
    id: 43,
    governorate: 'daraa',
    nameAr: 'فرع درعا الرئيسي',
    nameEn: 'Daraa Main Branch',
    addressAr: 'بوابة الجمارك - جانب استراحة النخيل',
    addressEn: 'Customs Gate, next to Al-Nakhil Rest House',
    phone: '0989313300',
    status: 'ACTIVE',
  },
  {
    id: 44,
    governorate: 'daraa',
    nameAr: 'فرع الصنمين',
    nameEn: 'Sanamein Branch',
    addressAr: 'الطريق الرئيسي مدخل الكتيبة الطبية',
    addressEn: 'Main Road, Medical Battalion Entrance',
    phone: '0992777401',
    status: 'ACTIVE',
  },
  {
    id: 45,
    governorate: 'daraa',
    nameAr: 'فرع الحيرة',
    nameEn: 'Al-Hira Branch',
    addressAr: 'جنوب المسجد الكبير بجانب مجوهرات وأعاريت',
    addressEn: 'South of Grand Mosque, next to jewelry shops',
    phone: '0934393810',
    status: 'ACTIVE',
  },
  {
    id: 46,
    governorate: 'daraa',
    nameAr: 'فرع نصيب',
    nameEn: 'Nasib Branch',
    addressAr: 'غرب باب الهوى 350 متر',
    addressEn: '350m west of Bab Al-Hawa',
    phone: '0934393811',
    status: 'ACTIVE',
  },
  {
    id: 47,
    governorate: 'daraa',
    nameAr: 'فرع الحراك',
    nameEn: 'Hirak Branch',
    addressAr: 'وسط البلد',
    addressEn: 'Downtown',
    phone: '0934393381',
    status: 'HIDDEN',
  },
  {
    id: 48,
    governorate: 'daraa',
    nameAr: 'فرع صمدا',
    nameEn: 'Samda Branch',
    addressAr: 'صمدا الطريق العام مقابل مفرق الغربا',
    addressEn: 'Samda, Main Road, opposite Gharba Junction',
    phone: '0989313300',
    status: 'HIDDEN',
  },
  {
    id: 49,
    governorate: 'daraa',
    nameAr: 'فرع واسط',
    nameEn: 'Wasit Branch',
    addressAr: 'وسط البلد',
    addressEn: 'Downtown',
    phone: '0934393381',
    status: 'ACTIVE',
  },
  {
    id: 50,
    governorate: 'daraa',
    nameAr: 'فرع جاسم',
    nameEn: 'Jasim Branch',
    addressAr: 'جاسم دوار أم تمام',
    addressEn: 'Jasim, Um Tammam Roundabout',
    phone: '0941879079',
    status: 'ACTIVE',
  },
  {
    id: 51,
    governorate: 'daraa',
    nameAr: 'فرع الكرك',
    nameEn: 'Karak Branch',
    addressAr: 'الكرك الشرق وسط البلد الشارع الرئيسي محل رقم 1',
    addressEn: 'East Karak, Downtown, Main Street, Shop No. 1',
    phone: '0994873052',
    status: 'HIDDEN',
  },
  {
    id: 52,
    governorate: 'daraa',
    nameAr: 'فرع درعا المدينة',
    nameEn: 'Daraa City Branch',
    addressAr: 'شمال دوار البقر 50 متر',
    addressEn: '50m north of Al-Baqar Roundabout',
    phone: '0936055375',
    status: 'ACTIVE',
  },
  {
    id: 53,
    governorate: 'daraa',
    nameAr: 'فرع المسيفرة',
    nameEn: 'Msayfra Branch',
    addressAr: 'المسيفرة وسط البلدة قرب دوار الشهداء',
    addressEn: 'Msayfra, town center near Martyrs Roundabout',
    phone: '0937412279',
    status: 'ACTIVE',
  },

  // ── اللاذقية ──────────────────────────────────────────────
  {
    id: 54,
    governorate: 'latakia',
    nameAr: 'فرع اللاذقية',
    nameEn: 'Latakia Branch',
    addressAr: 'جانب هارون مالك بن الهجرة والجوازات',
    addressEn: 'Next to Haroun, near Immigration & Passports',
    phone: '0997644907',
    status: 'ACTIVE',
  },
  {
    id: 55,
    governorate: 'latakia',
    nameAr: 'فرع اللاذقية - الزراعة',
    nameEn: 'Latakia - Ziraa Branch',
    addressAr: 'الزراعة بجانب كارية حورية',
    addressEn: 'Ziraa area, next to Houriya Gas Station',
    phone: '0932655145',
    status: 'ACTIVE',
  },

  // ── طرطوس ──────────────────────────────────────────────────
  {
    id: 56,
    governorate: 'tartous',
    nameAr: 'فرع طرطوس - القدموس',
    nameEn: 'Tartous - Qadmous Branch',
    addressAr: 'دخلة كراج القدموس مقابل الحديقة العامة',
    addressEn: 'Qadmous Garage entrance, opposite Public Park',
    phone: '0949392998',
    status: 'ACTIVE',
  },
  {
    id: 57,
    governorate: 'tartous',
    nameAr: 'فرع طرطوس',
    nameEn: 'Tartous Branch',
    addressAr: 'شارع التوتر مقابل مقهى القلعة الإسلامي',
    addressEn: 'Tawtar Street, opposite Al-Qala Islamic Cafe',
    phone: '0968342284',
    status: 'ACTIVE',
  },

  // ── دير الزور ──────────────────────────────────────────────
  {
    id: 58,
    governorate: 'deir_ez_zor',
    nameAr: 'فرع الميادين',
    nameEn: 'Mayadin Branch',
    addressAr: 'جانب تنظيمات القدموس',
    addressEn: 'Next to Qadmous Transport',
    phone: '0998272827',
    status: 'ACTIVE',
  },
  {
    id: 59,
    governorate: 'deir_ez_zor',
    nameAr: 'فرع الميادين 2',
    nameEn: 'Mayadin Branch 2',
    addressAr: 'شارع أنس بن مالك',
    addressEn: 'Anas bin Malik Street',
    phone: '0989400842',
    status: 'ACTIVE',
  },
  {
    id: 60,
    governorate: 'deir_ez_zor',
    nameAr: 'فرع دير الزور - الفوزية',
    nameEn: 'Deir ez-Zor - Fawziya Branch',
    addressAr: 'الفوزية الشارع العام مقابل الوحدة الإرشادية جانب محلات عيسى العود',
    addressEn: 'Fawziya, Main Street, opposite Guidance Unit, next to Issa Al-Oud shops',
    phone: '0988075264',
    status: 'HIDDEN',
  },
  {
    id: 61,
    governorate: 'deir_ez_zor',
    nameAr: 'فرع دير الزور',
    nameEn: 'Deir ez-Zor Branch',
    addressAr: 'دوار الحويجة جانب مركز سيريانيل',
    addressEn: 'Huweija Roundabout, next to Syriatel Center',
    phone: '0989400890',
    status: 'ACTIVE',
  },

  // ── الرقة ──────────────────────────────────────────────────
  {
    id: 62,
    governorate: 'raqqa',
    nameAr: 'فرع الرقة',
    nameEn: 'Raqqa Branch',
    addressAr: 'وسط البلد',
    addressEn: 'Downtown',
    phone: '0932963805',
    status: 'ACTIVE',
  },

  // ── الحسكة والقامشلي ──────────────────────────────────────
  {
    id: 63,
    governorate: 'hasakah',
    nameAr: 'فرع الحسكة',
    nameEn: 'Hasakah Branch',
    addressAr: 'المقيق جانب دوار ساريخ',
    addressEn: 'Al-Muqayyiq, next to Sarikh Roundabout',
    phone: '0988870174',
    status: 'ACTIVE',
  },
  {
    id: 64,
    governorate: 'hasakah',
    nameAr: 'فرع الحسكة - سينما القاهرة',
    nameEn: 'Hasakah - Cairo Cinema Branch',
    addressAr: 'شارع سينما القاهرة جانب قوت سنتر',
    addressEn: 'Cairo Cinema Street, next to Qout Center',
    phone: '0955968650',
    status: 'HIDDEN',
  },
  {
    id: 65,
    governorate: 'hasakah',
    nameAr: 'فرع الحسكة - مربوع',
    nameEn: 'Hasakah - Marbou Branch',
    addressAr: 'مربوع مقابل مدرسة الأمل',
    addressEn: 'Marbou, opposite Al-Amal School',
    phone: '0988128320',
    status: 'HIDDEN',
  },
  {
    id: 66,
    governorate: 'hasakah',
    nameAr: 'فرع القامشلي - سوق عزرا 1',
    nameEn: 'Qamishli - Azra Market Branch 1',
    addressAr: 'سوق عزرا بجانب المؤسسة العسكرية',
    addressEn: 'Azra Market, next to Military Establishment',
    phone: '0989400840',
    status: 'HIDDEN',
  },
  {
    id: 67,
    governorate: 'hasakah',
    nameAr: 'فرع القامشلي - سوق عزرا 2',
    nameEn: 'Qamishli - Azra Market Branch 2',
    addressAr: 'سوق عزرا',
    addressEn: 'Azra Market',
    phone: '0989400831',
    status: 'HIDDEN',
  },
  {
    id: 68,
    governorate: 'hasakah',
    nameAr: 'فرع القامشلي - الصالة الملكية',
    nameEn: 'Qamishli - Royal Hall Branch',
    addressAr: 'جانب الصالة الملكية',
    addressEn: 'Next to Royal Hall',
    phone: '0937757715',
    status: 'HIDDEN',
  },
  {
    id: 69,
    governorate: 'tartous',
    nameAr: 'فرع طرطوس - طريق حمص',
    nameEn: 'Tartous - Homs Road Branch',
    addressAr: 'طريق حمص',
    addressEn: 'Homs Road',
    phone: '0937771381',
    status: 'HIDDEN',
  },
];
